version: "2"
checks:
  similar-code:
    config:
      threshold: 90
exclude_patterns:
- "docs/"
- "scripts/"
- "examples/"
- "src/__mocks__"
- "dist/"
- "**/node_modules/"
- "**/*.test.js"
- "**/*.stories.js"
