pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success~=build
      - check-success=UI Tests
      - check-success=codeclimate
      - check-success-or-neutral~=LGTM
    actions:
      merge:
        method: rebase

