export default {
  modal: "chrome-modal",
  overlay: "chrome-overlay",
  container: "chrome-container",
  highlight: "chrome-highlight",
  content: "chrome-content",
  containerOpen: "chrome-containerOpen",
  input: "chrome-input",
  inputOpen: "chrome-inputOpen",
  inputFocused: "chrome-inputFocused",
  suggestionsContainer: "chrome-suggestionsContainer",
  suggestionsContainerOpen: "chrome-suggestionsContainerOpen",
  suggestionsList: "chrome-suggestionsList",
  suggestion: "chrome-suggestion",
  suggestionFirst: "chrome-suggestionFirst",
  suggestionHighlighted: "chrome-suggestionHighlighted",
  sectionContainer: "chrome-sectionContainer",
  sectionContainerFirst: "chrome-sectionContainerFirst",
  sectionTitle: "chrome-sectionTitle"
};
